[workspace]
resolver = "3"
members = ["aperture","library/aperture-core", "library/aperture-driver"]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
